name: SonarCloud Code Analysis

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
env:
  ORG_GRADLE_PROJECT_contrastArtifactoryUser: ${{ secrets.CONTRAST_ARTIFACTORY_USER }}
  ORG_GRADLE_PROJECT_contrastArtifactoryPassword: ${{ secrets.CONTRAST_ARTIFACTORY_PASSWORD }}

permissions:
  contents: read

jobs:
  sonar-cloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: |
          make coverageVerification
      - name: 🔊 SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 #v2.4.2
        with:
          arguments: sonar --info --stacktrace
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: test-reports
          path: build/reports/tests