name: Validate

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate
        env:
          ORG_GRADLE_PROJECT_contrastArtifactoryUser: ${{ secrets.CONTRAST_ARTIFACTORY_USER }}
          ORG_GRADLE_PROJECT_contrastArtifactoryPassword: ${{ secrets.CONTRAST_ARTIFACTORY_PASSWORD }}
        run: make lint